/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HealthFirstPharmacy_Hague.GUI;

import HealthFirstPharmacy_Hague.medicines.Drug;
import HealthFirstPharmacy_Hague.medicines.Inventory;
import HealthFirstPharmacy_Hague.users.UsersList;
import java.awt.FlowLayout;
import javax.swing.table.DefaultTableModel;





/**
 *
 * @author joehague
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        baseInventoryPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_inventory = new javax.swing.JTable();
        baseStaffPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_staff = new javax.swing.JTable();
        panel_manaheStockForm1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        text_staffID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_selectedStaffName = new javax.swing.JTextField();
        button_updateStaff = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text_selectedStaffEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_selectedStaffAddress = new javax.swing.JTextField();
        button_deleteStaff = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        text_newStaffFirstName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        text_newStaffLastName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        text_newStaffEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        text_newStaffSalary = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        text_newStaffAddress1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        text_newStaffAddress2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        text_newStaffAddress3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        text_newStaffMobile = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        text_newStaffUserName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        text_newStaffPassword = new javax.swing.JTextField();
        button_order3 = new javax.swing.JButton();
        combo_newStaff = new javax.swing.JComboBox<>();
        baseManageStockPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_inventoryBasic = new javax.swing.JTable();
        panel_manaheStockForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text_manageStock_replenishAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        text_manageStock_selectedItem = new javax.swing.JTextField();
        button_order = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        text_manageStock_newItemName = new javax.swing.JTextField();
        slider_newItemQuantity = new javax.swing.JSlider();
        label_newItemQuantity = new javax.swing.JLabel();
        button_addNewstock = new javax.swing.JButton();
        baseAddPatientPanel = new javax.swing.JPanel();
        baseAddStaffPanel = new javax.swing.JPanel();
        baseReportsPanel = new javax.swing.JPanel();
        header = new javax.swing.JMenuBar();
        header_menuFile = new javax.swing.JMenu();
        menu_Logout = new javax.swing.JMenuItem();
        menu_headerInventory = new javax.swing.JMenu();
        menu_viewInventory = new javax.swing.JMenuItem();
        menu_addStock = new javax.swing.JMenuItem();
        menuButton_viewPatients = new javax.swing.JMenu();
        menu_addPatient = new javax.swing.JMenuItem();
        menu_viewPatients = new javax.swing.JMenuItem();
        header_menuStaff = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_addStaff = new javax.swing.JMenuItem();
        header_menuReports = new javax.swing.JMenu();
        menu_dispensedReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        baseInventoryPanel.setBackground(new java.awt.Color(255, 204, 102));

        table_inventory.setModel(Inventory.getInventoryTableModel());
        table_inventory.setRowHeight(30);
        table_inventory.setRowMargin(10);
        table_inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_inventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_inventory);

        javax.swing.GroupLayout baseInventoryPanelLayout = new javax.swing.GroupLayout(baseInventoryPanel);
        baseInventoryPanel.setLayout(baseInventoryPanelLayout);
        baseInventoryPanelLayout.setHorizontalGroup(
            baseInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseInventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
                .addContainerGap())
        );
        baseInventoryPanelLayout.setVerticalGroup(
            baseInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseInventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addContainerGap())
        );

        baseStaffPanel.setBackground(new java.awt.Color(255, 102, 102));

        table_staff.setAutoCreateRowSorter(true);
        table_staff.setModel(UsersList.getStaffList());
        table_staff.setRowHeight(30);
        table_staff.setRowMargin(10);
        table_staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_staffMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_staffMousePressed(evt);
            }
        });
        table_staff.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                table_staffComponentShown(evt);
            }
        });
        jScrollPane3.setViewportView(table_staff);

        panel_manaheStockForm1.setEnabled(table_inventoryBasic.getSelectedRow() > -1 ? true : false);

        jLabel5.setText("Staff ID");

        text_staffID.setEditable(false);
        text_staffID.setEnabled(false);

        jLabel6.setText("Selected Staff Member");

        text_selectedStaffName.setEnabled(false);

        button_updateStaff.setBackground(new java.awt.Color(153, 255, 102));
        button_updateStaff.setText("Update");
        button_updateStaff.setEnabled(table_inventoryBasic.getSelectedRow() > -1 ? true : false);
        button_updateStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateStaffActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Add Stock - Selected Drug Stock");

        jLabel9.setText("Email");

        jLabel10.setText("Address");

        button_deleteStaff.setBackground(new java.awt.Color(255, 0, 51));
        button_deleteStaff.setText("Delete");
        button_deleteStaff.setEnabled(table_inventoryBasic.getSelectedRow() > -1 ? true : false);
        button_deleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_manaheStockForm1Layout = new javax.swing.GroupLayout(panel_manaheStockForm1);
        panel_manaheStockForm1.setLayout(panel_manaheStockForm1Layout);
        panel_manaheStockForm1Layout.setHorizontalGroup(
            panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_manaheStockForm1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_manaheStockForm1Layout.createSequentialGroup()
                        .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_staffID, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_selectedStaffName)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_selectedStaffAddress)
                            .addGroup(panel_manaheStockForm1Layout.createSequentialGroup()
                                .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(text_selectedStaffEmail)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panel_manaheStockForm1Layout.createSequentialGroup()
                        .addComponent(button_updateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_deleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_manaheStockForm1Layout.setVerticalGroup(
            panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_manaheStockForm1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_selectedStaffEmail)
                    .addComponent(text_selectedStaffName))
                .addGap(15, 15, 15)
                .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_selectedStaffAddress)
                    .addComponent(text_staffID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(panel_manaheStockForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_updateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_deleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel8.setText("First Name");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Add New Staff Member");

        jLabel12.setText("Last Name");

        jLabel13.setText("Email");

        jLabel14.setText("Salary");

        text_newStaffSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_newStaffSalaryActionPerformed(evt);
            }
        });

        jLabel15.setText("House Number and Street");

        jLabel16.setText("Town");

        jLabel17.setText("Postcode");

        jLabel18.setText("Mobile");

        jLabel19.setText("UserName");

        jLabel20.setText("Password");

        button_order3.setBackground(new java.awt.Color(153, 255, 102));
        button_order3.setText("Save");
        button_order3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_order3ActionPerformed(evt);
            }
        });

        combo_newStaff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Manager", "Pharmacist" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_newStaffEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_newStaffSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_newStaffLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_newStaffFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_newStaffMobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_newStaffAddress3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_newStaffAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_newStaffAddress1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(text_newStaffPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_newStaffUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(combo_newStaff, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_order3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_newStaffFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_newStaffLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_newStaffEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_newStaffUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_newStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_newStaffSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_newStaffAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_newStaffAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_newStaffAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_newStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_newStaffMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(button_order3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout baseStaffPanelLayout = new javax.swing.GroupLayout(baseStaffPanel);
        baseStaffPanel.setLayout(baseStaffPanelLayout);
        baseStaffPanelLayout.setHorizontalGroup(
            baseStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseStaffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(baseStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_manaheStockForm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        baseStaffPanelLayout.setVerticalGroup(
            baseStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseStaffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(baseStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addGroup(baseStaffPanelLayout.createSequentialGroup()
                        .addComponent(panel_manaheStockForm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        baseManageStockPanel.setBackground(new java.awt.Color(51, 0, 255));

        table_inventoryBasic.setAutoCreateRowSorter(true);
        table_inventoryBasic.setModel(Inventory.getInventoryBasicList());
        table_inventoryBasic.setRowHeight(30);
        table_inventoryBasic.setRowMargin(10);
        table_inventoryBasic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_inventoryBasicMouseClicked(evt);
            }
        });
        table_inventoryBasic.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                table_inventoryBasicComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(table_inventoryBasic);

        panel_manaheStockForm.setEnabled(table_inventoryBasic.getSelectedRow() > -1 ? true : false);

        jLabel1.setText("Amount Required to replenish stock");

        text_manageStock_replenishAmount.setText(table_inventoryBasic.getSelectedRow() >= 0 ? table_inventoryBasic.getValueAt(table_inventory.getSelectedRow(),0).toString() : ""
        );

        jLabel2.setText("Selected Item");

        text_manageStock_selectedItem.setText(table_inventoryBasic.getSelectedRow() >= 0 ? table_inventoryBasic.getValueAt(table_inventory.getSelectedRow(),0).toString() : ""
        );
        text_manageStock_selectedItem.setEnabled(false);

        button_order.setText("Order");
        button_order.setEnabled(table_inventoryBasic.getSelectedRow() > -1 ? true : false);
        button_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_orderActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add Stock - Selected Drug Stock");

        javax.swing.GroupLayout panel_manaheStockFormLayout = new javax.swing.GroupLayout(panel_manaheStockForm);
        panel_manaheStockForm.setLayout(panel_manaheStockFormLayout);
        panel_manaheStockFormLayout.setHorizontalGroup(
            panel_manaheStockFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_manaheStockFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_manaheStockFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_manaheStockFormLayout.createSequentialGroup()
                        .addGroup(panel_manaheStockFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_order, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_manaheStockFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_manageStock_replenishAmount)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                            .addGroup(panel_manaheStockFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_manageStock_selectedItem)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 306, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_manaheStockFormLayout.setVerticalGroup(
            panel_manaheStockFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_manaheStockFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_manageStock_selectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_manageStock_replenishAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_order, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setText("Item Name");

        slider_newItemQuantity.setValue(0);
        slider_newItemQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_newItemQuantityStateChanged(evt);
            }
        });

        label_newItemQuantity.setText("Quantity: " + slider_newItemQuantity.getValue());

        button_addNewstock.setText("Add New Stock");
        button_addNewstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addNewstockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(button_addNewstock, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(label_newItemQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text_manageStock_newItemName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(slider_newItemQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_manageStock_newItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_newItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(slider_newItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_addNewstock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout baseManageStockPanelLayout = new javax.swing.GroupLayout(baseManageStockPanel);
        baseManageStockPanel.setLayout(baseManageStockPanelLayout);
        baseManageStockPanelLayout.setHorizontalGroup(
            baseManageStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseManageStockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(baseManageStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_manaheStockForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        baseManageStockPanelLayout.setVerticalGroup(
            baseManageStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseManageStockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(baseManageStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(baseManageStockPanelLayout.createSequentialGroup()
                        .addComponent(panel_manaheStockForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        baseAddPatientPanel.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout baseAddPatientPanelLayout = new javax.swing.GroupLayout(baseAddPatientPanel);
        baseAddPatientPanel.setLayout(baseAddPatientPanelLayout);
        baseAddPatientPanelLayout.setHorizontalGroup(
            baseAddPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        baseAddPatientPanelLayout.setVerticalGroup(
            baseAddPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        baseAddStaffPanel.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout baseAddStaffPanelLayout = new javax.swing.GroupLayout(baseAddStaffPanel);
        baseAddStaffPanel.setLayout(baseAddStaffPanelLayout);
        baseAddStaffPanelLayout.setHorizontalGroup(
            baseAddStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        baseAddStaffPanelLayout.setVerticalGroup(
            baseAddStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        baseReportsPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout baseReportsPanelLayout = new javax.swing.GroupLayout(baseReportsPanel);
        baseReportsPanel.setLayout(baseReportsPanelLayout);
        baseReportsPanelLayout.setHorizontalGroup(
            baseReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        baseReportsPanelLayout.setVerticalGroup(
            baseReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        header_menuFile.setText("File");

        menu_Logout.setText("Log out");
        menu_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_LogoutActionPerformed(evt);
            }
        });
        header_menuFile.add(menu_Logout);

        header.add(header_menuFile);

        menu_headerInventory.setText("Inventory");

        menu_viewInventory.setText("View Inventory");
        menu_viewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewInventoryActionPerformed(evt);
            }
        });
        menu_headerInventory.add(menu_viewInventory);

        menu_addStock.setText("Manage Stock");
        menu_addStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addStockActionPerformed(evt);
            }
        });
        menu_headerInventory.add(menu_addStock);

        header.add(menu_headerInventory);

        menuButton_viewPatients.setText("Patients");

        menu_addPatient.setText("Add Patient");
        menu_addPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addPatientActionPerformed(evt);
            }
        });
        menuButton_viewPatients.add(menu_addPatient);

        menu_viewPatients.setText("View Patients");
        menu_viewPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_viewPatientsActionPerformed(evt);
            }
        });
        menuButton_viewPatients.add(menu_viewPatients);

        header.add(menuButton_viewPatients);

        header_menuStaff.setText("Staff");

        jMenuItem1.setText("Add Staff");
        header_menuStaff.add(jMenuItem1);

        menu_addStaff.setText("View Staff");
        menu_addStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addStaffActionPerformed(evt);
            }
        });
        header_menuStaff.add(menu_addStaff);

        header.add(header_menuStaff);

        header_menuReports.setText("Reports");

        menu_dispensedReport.setText("Dispensed Medicines");
        menu_dispensedReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_dispensedReportActionPerformed(evt);
            }
        });
        header_menuReports.add(menu_dispensedReport);

        header.add(header_menuReports);

        setJMenuBar(header);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baseInventoryPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(baseStaffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(baseManageStockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(baseAddPatientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(baseAddStaffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(baseReportsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baseInventoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(baseStaffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(baseManageStockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(baseAddPatientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(baseAddStaffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(baseReportsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_dispensedReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_dispensedReportActionPerformed
        baseInventoryPanel.setVisible(false);
        baseStaffPanel.setVisible(false);
        baseManageStockPanel.setVisible(false);
        baseAddStaffPanel.setVisible(false);
        baseAddPatientPanel.setVisible(false);
        baseReportsPanel.setVisible(true);
    }//GEN-LAST:event_menu_dispensedReportActionPerformed

    private void menu_addPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addPatientActionPerformed
        baseInventoryPanel.setVisible(false);
        baseReportsPanel.setVisible(false);
        baseStaffPanel.setVisible(false);
        baseManageStockPanel.setVisible(false);
        baseAddStaffPanel.setVisible(false);
        baseAddPatientPanel.setVisible(true);
    }//GEN-LAST:event_menu_addPatientActionPerformed

    private void menu_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_LogoutActionPerformed
        this.setVisible(false);
        LogInFrame logInFrame = new LogInFrame();
        logInFrame.toggleLogin();
        
    }//GEN-LAST:event_menu_LogoutActionPerformed

    private void menu_viewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewInventoryActionPerformed
        
        baseAddPatientPanel.setVisible(false);
        baseStaffPanel.setVisible(false);
        baseReportsPanel.setVisible(false);
        baseAddStaffPanel.setVisible(false);
        baseManageStockPanel.setVisible(false);
        baseAddStaffPanel.setVisible(false);
        baseInventoryPanel.setVisible(true);
          
          
        
    }//GEN-LAST:event_menu_viewInventoryActionPerformed

    private void menu_viewPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_viewPatientsActionPerformed
        baseInventoryPanel.setVisible(false);
        baseManageStockPanel.setVisible(false);
        baseReportsPanel.setVisible(false);
        baseAddStaffPanel.setVisible(false);
        baseStaffPanel.setVisible(false);
        baseAddPatientPanel.setVisible(true);
        
        
    }//GEN-LAST:event_menu_viewPatientsActionPerformed

    private void menu_addStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addStockActionPerformed
        baseInventoryPanel.setVisible(false);
        baseAddStaffPanel.setVisible(false);
        baseReportsPanel.setVisible(false);
        baseAddPatientPanel.setVisible(false);
        baseStaffPanel.setVisible(false);
        baseManageStockPanel.setVisible(true);
    }//GEN-LAST:event_menu_addStockActionPerformed

    private void menu_addStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addStaffActionPerformed
        baseInventoryPanel.setVisible(false);
        baseAddStaffPanel.setVisible(false);
        baseManageStockPanel.setVisible(false);
        baseReportsPanel.setVisible(false);
        baseAddPatientPanel.setVisible(false);
        baseStaffPanel.setVisible(true);
    }//GEN-LAST:event_menu_addStaffActionPerformed

    private void table_inventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_inventoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_inventoryMouseClicked

    private void table_inventoryBasicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_inventoryBasicMouseClicked
        text_manageStock_selectedItem.setText(table_inventoryBasic.getValueAt(table_inventoryBasic.getSelectedRow(), 0).toString());
        text_manageStock_replenishAmount.setText(table_inventoryBasic.getValueAt(table_inventoryBasic.getSelectedRow(), 2).toString());
        button_order.setEnabled(true);
    }//GEN-LAST:event_table_inventoryBasicMouseClicked

    private void table_inventoryBasicComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_table_inventoryBasicComponentShown
        
    }//GEN-LAST:event_table_inventoryBasicComponentShown

    private void button_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_orderActionPerformed
        Drug drug = Inventory.getDrug(table_inventoryBasic.getValueAt(table_inventoryBasic.getSelectedRow(), 0).toString());
        int quantity = Integer.valueOf(text_manageStock_replenishAmount.getText());
        drug.addStock(quantity);
        table_inventoryBasic.setModel(Inventory.getInventoryBasicList());
        table_inventory.setModel(Inventory.getInventoryTableModel());
        int reducedAmount = Integer.valueOf(text_manageStock_replenishAmount.getText()) - quantity;
        text_manageStock_replenishAmount.setText(Integer.toString(reducedAmount));
        button_order.setEnabled(false);
    }//GEN-LAST:event_button_orderActionPerformed

    private void slider_newItemQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_newItemQuantityStateChanged
        label_newItemQuantity.setText("Quantity: " + slider_newItemQuantity.getValue());
    }//GEN-LAST:event_slider_newItemQuantityStateChanged

    private void button_addNewstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addNewstockActionPerformed
        Drug drug = new Drug(text_manageStock_newItemName.getText(),slider_newItemQuantity.getValue(),10.99f);
        Inventory.addDrugs(drug);
        table_inventoryBasic.setModel(Inventory.getInventoryBasicList());
        table_inventory.setModel(Inventory.getInventoryTableModel());
        text_manageStock_newItemName.setText("");
        slider_newItemQuantity.setValue(0);
    }//GEN-LAST:event_button_addNewstockActionPerformed

    private void table_staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_staffMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_staffMouseClicked

    private void table_staffComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_table_staffComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_table_staffComponentShown

    private void button_updateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_updateStaffActionPerformed

    private void button_deleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_deleteStaffActionPerformed

    private void button_order3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_order3ActionPerformed
        UsersList.addPerson(text_newStaffFirstName.getText(), text_newStaffLastName.getText(), text_newStaffEmail.getText(), text_newStaffAddress1.getText() + ", " + text_newStaffAddress2.getText() + ", " + text_newStaffAddress3.getText(),24000.00f, text_newStaffUserName.getText(), text_newStaffPassword.getText().toCharArray() , combo_newStaff.getSelectedItem().toString());
        table_staff.setModel(UsersList.getStaffList());
    }//GEN-LAST:event_button_order3ActionPerformed

    private void text_newStaffSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_newStaffSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_newStaffSalaryActionPerformed

    private void table_staffMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_staffMousePressed
//        text_staffID.setText() = table_staff.getValueAt(1,0);
    }//GEN-LAST:event_table_staffMousePressed

    /**
     * @param args the command line arguments
     */
    public static void start(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel baseAddPatientPanel;
    private javax.swing.JPanel baseAddStaffPanel;
    private javax.swing.JPanel baseInventoryPanel;
    private javax.swing.JPanel baseManageStockPanel;
    private javax.swing.JPanel baseReportsPanel;
    private javax.swing.JPanel baseStaffPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_addNewstock;
    private javax.swing.JButton button_deleteStaff;
    private javax.swing.JButton button_order;
    private javax.swing.JButton button_order3;
    private javax.swing.JButton button_updateStaff;
    private javax.swing.JComboBox<String> combo_newStaff;
    private javax.swing.JMenuBar header;
    private javax.swing.JMenu header_menuFile;
    private javax.swing.JMenu header_menuReports;
    private javax.swing.JMenu header_menuStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_newItemQuantity;
    private javax.swing.JMenu menuButton_viewPatients;
    private javax.swing.JMenuItem menu_Logout;
    private javax.swing.JMenuItem menu_addPatient;
    private javax.swing.JMenuItem menu_addStaff;
    private javax.swing.JMenuItem menu_addStock;
    private javax.swing.JMenuItem menu_dispensedReport;
    private javax.swing.JMenu menu_headerInventory;
    private javax.swing.JMenuItem menu_viewInventory;
    private javax.swing.JMenuItem menu_viewPatients;
    private javax.swing.JPanel panel_manaheStockForm;
    private javax.swing.JPanel panel_manaheStockForm1;
    private javax.swing.JSlider slider_newItemQuantity;
    private javax.swing.JTable table_inventory;
    private javax.swing.JTable table_inventoryBasic;
    private javax.swing.JTable table_staff;
    private javax.swing.JTextField text_manageStock_newItemName;
    private javax.swing.JTextField text_manageStock_replenishAmount;
    private javax.swing.JTextField text_manageStock_selectedItem;
    private javax.swing.JTextField text_newStaffAddress1;
    private javax.swing.JTextField text_newStaffAddress2;
    private javax.swing.JTextField text_newStaffAddress3;
    private javax.swing.JTextField text_newStaffEmail;
    private javax.swing.JTextField text_newStaffFirstName;
    private javax.swing.JTextField text_newStaffLastName;
    private javax.swing.JTextField text_newStaffMobile;
    private javax.swing.JTextField text_newStaffPassword;
    private javax.swing.JTextField text_newStaffSalary;
    private javax.swing.JTextField text_newStaffUserName;
    private javax.swing.JTextField text_selectedStaffAddress;
    private javax.swing.JTextField text_selectedStaffEmail;
    private javax.swing.JTextField text_selectedStaffName;
    private javax.swing.JTextField text_staffID;
    // End of variables declaration//GEN-END:variables
}
